### ISSUE TITLE
cant bind default address.....

### ISSUE THREAD

**Issue by baz0okq** [ilyarolf/AiogramShopBot#40]
Hi.

ngrok running

![20240611_011340](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/9a682ba7-64d9-4913-ab8e-54a738a6c262)

In env

![20240611_011415](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/5e335bba-9d24-487e-89a4-8a47e46a6890)

And i have that error

![20240611_011534](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/b1fb7ba9-54be-4693-a31d-ca72c68264b8)

Anyone have idea?

**Comment by ilyarolf** [comment]
Hello @baz0okq, now you no longer need to run ngrok manually, it runs when you run the bot in the ngrok_executor.py file. I think this is not the main problem when running the bot, according to the console, you still have some problems in the db.py file

**Comment by ilyarolf** [comment]
@baz0okq Is your problem still relevant?

**Comment by baz0okq** [comment]
Yes mate. Still the same, broke all my head cant find any mistake.

**Comment by ilyarolf** [comment]
@baz0okq have you tried deploying the bot through docker?

**Comment by baz0okq** [comment]
Fill the docker-compose.yaml and run docker-compose up and its solve problem but give me another one :D 

![20240619_132558](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/1086ada1-44f6-4af1-9452-56b9fdc8c69a)

![20240619_133822](https://github.com/ilyarolf/AiogramShopBot/assets/156255251/62d9fe82-288f-4631-b7fc-ded641996df0)

**Comment by ilyarolf** [comment]
By the logs you have some other version of Aiogram even in the docker image, although it should be 3.1.1. You can try not to build the docker image from source, but use the image from Dockerhub.

> https://hub.docker.com/r/ilyarolf/aiogram-shop-bot


or

> https://hub.docker.com/r/ilyarolf/aiogram-shop-bot-encrypted


In this case your docker-compose.yml will look like this:
```
version: "3.8"
services:
  bot:
    image: "ilyarolf/aiogram-shop-bot"
    container_name: 'AiogramShopBot'
    environment:
      WEBHOOK_PATH: ""
      WEBAPP_HOST: "0.0.0.0" # Don't touch this
      WEBAPP_PORT: 5000 # Here your port
      TOKEN: "1234567890:QWER.....TYI" # Here your bot token from botfather
      NGROK_TOKEN: 'NGROK_TOKEN_HERE' # Here your ngrok token from ngrok.com
      ADMIN_ID_LIST: "12345678,87654321" # Telegram ID's for admins;
      SUPPORT_LINK: "https://t.me/YourUsername"
      DB_NAME: "database.db" # Here your database name
      PAGE_ENTRIES: 20 # Items per page
    ports:
      - "4040:4040"
      - "5000:5000" # ${WEBAPP_PORT}:${WEBAPP_PORT}
    expose:
      - 4040
      - 5000 # ${WEBAPP_PORT}
    volumes:
      - /AiogramShopBot:/bot/data
    command: ["python", "-u", "run.py"]

volumes:
  AiogramShopBot:
```
